from __future__ import annotations

import argparse
import colorsys
import re
import tkinter as tk
from pathlib import Path
from tkinter import colorchooser, messagebox, ttk


ROOT_DIR = Path(__file__).resolve().parent
PALETTE_PATH = ROOT_DIR / "static" / "home_menu_palette.css"

MENU_GROUPS = [
    (
        "Operativa",
        [
            ("home-menu-card-sales", "Nueva factura", "#db9648"),
            ("home-menu-card-purchases", "Nueva compra", "#e7aa61"),
            ("home-menu-card-expenses", "Gasto libre", "#f2bd79"),
            ("home-menu-card-inventory", "Inventario", "#f9cf9b"),
        ],
    ),
    (
        "Consulta",
        [
            ("home-menu-card-history-sales", "Historial Facturas", "#6faee2"),
            ("home-menu-card-history-purchases", "Historial Compras", "#8fc3f1"),
            ("home-menu-card-history-expenses", "Historial Gastos", "#b9dcff"),
            ("home-menu-card-user", "Usuario", "#dbeeff"),
        ],
    ),
    (
        "Administracion",
        [
            ("home-menu-card-settings", "Configuracion", "#d3d3d3"),
            ("home-menu-card-analytics", "Analisis", "#ededed"),
        ],
    ),
]

CLASS_ORDER = [css_class for _, items in MENU_GROUPS for css_class, _, _ in items]
DEFAULT_COLORS = {css_class: color for _, items in MENU_GROUPS for css_class, _, color in items}


def normalize_hex(value: str) -> str:
    raw = (value or "").strip().lstrip("#")
    if len(raw) == 3:
        raw = "".join(ch * 2 for ch in raw)
    if len(raw) != 6 or any(ch not in "0123456789abcdefABCDEF" for ch in raw):
        raise ValueError("Color HEX no valido")
    return f"#{raw.lower()}"


def hex_to_rgb(value: str) -> tuple[int, int, int]:
    value = normalize_hex(value)
    return tuple(int(value[i:i + 2], 16) for i in (1, 3, 5))


def rgb_to_hex(rgb: tuple[int, int, int]) -> str:
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def derive_border(fill_hex: str) -> str:
    r, g, b = hex_to_rgb(fill_hex)
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    darker_l = max(0.0, l - 0.12)
    darker_s = min(1.0, s + 0.04)
    rgb = colorsys.hls_to_rgb(h, darker_l, darker_s)
    return rgb_to_hex(tuple(round(channel * 255) for channel in rgb))


def relative_luminance(fill_hex: str) -> float:
    def channel(value: int) -> float:
        scaled = value / 255
        if scaled <= 0.03928:
            return scaled / 12.92
        return ((scaled + 0.055) / 1.055) ** 2.4

    r, g, b = hex_to_rgb(fill_hex)
    return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b)


def derive_text(fill_hex: str) -> str:
    return "#1f1f1f" if relative_luminance(fill_hex) > 0.45 else "#ffffff"


def load_palette() -> dict[str, str]:
    if not PALETTE_PATH.exists():
        return DEFAULT_COLORS.copy()

    content = PALETTE_PATH.read_text(encoding="utf-8")
    colors = DEFAULT_COLORS.copy()
    for css_class in CLASS_ORDER:
        match = re.search(
            rf"\.{re.escape(css_class)}\s*\{{[^}}]*background:\s*(#[0-9a-fA-F]{{3,6}})",
            content,
            re.MULTILINE,
        )
        if match:
            colors[css_class] = normalize_hex(match.group(1))
    return colors


def build_palette_css(colors: dict[str, str]) -> str:
    lines = [
        "/* Auto-generated by menu_color_editor.py. */",
        "",
        ".home-menu-card {",
        "  background-color: transparent !important;",
        "}",
        "",
    ]
    for css_class in CLASS_ORDER:
        fill = normalize_hex(colors[css_class])
        border = derive_border(fill)
        text = derive_text(fill)
        lines.extend(
            [
                f".{css_class} {{",
                f"  background: {fill} !important;",
                f"  border-color: {border} !important;",
                f"  color: {text} !important;",
                "}",
                "",
            ]
        )
    return "\n".join(lines).rstrip() + "\n"


def save_palette(colors: dict[str, str]) -> None:
    PALETTE_PATH.write_text(build_palette_css(colors), encoding="utf-8")


class MenuColorEditor:
    def __init__(self, root: tk.Tk) -> None:
        self.root = root
        self.root.title("Buen Yantar - Editor de colores menu")
        self.root.minsize(980, 720)
        self.colors = load_palette()
        self.color_vars: dict[str, tk.StringVar] = {}
        self.swatches: dict[str, tk.Label] = {}
        self.previews: dict[str, tk.Label] = {}
        self.status_var = tk.StringVar(value=f"Editando {PALETTE_PATH.name}")
        self._build_ui()
        self.refresh_all()

    def _build_ui(self) -> None:
        self.root.columnconfigure(0, weight=1)
        self.root.rowconfigure(1, weight=1)

        header = ttk.Frame(self.root, padding=(16, 16, 16, 10))
        header.grid(row=0, column=0, sticky="ew")
        header.columnconfigure(0, weight=1)

        ttk.Label(
            header,
            text="Editor de colores del menu principal",
            font=("Segoe UI", 16, "bold"),
        ).grid(row=0, column=0, sticky="w")
        ttk.Label(
            header,
            text="Cada boton usa un color solido. Guarda y recarga la pagina principal para ver cambios.",
        ).grid(row=1, column=0, sticky="w", pady=(4, 0))
        ttk.Label(
            header,
            text=str(PALETTE_PATH),
            foreground="#5b6470",
        ).grid(row=2, column=0, sticky="w", pady=(4, 0))

        notebook = ttk.Notebook(self.root)
        notebook.grid(row=1, column=0, sticky="nsew", padx=16, pady=(0, 10))

        editor_tab = ttk.Frame(notebook, padding=16)
        preview_tab = ttk.Frame(notebook, padding=16)
        notebook.add(editor_tab, text="Colores")
        notebook.add(preview_tab, text="Vista previa")

        self._build_editor_tab(editor_tab)
        self._build_preview_tab(preview_tab)

        footer = ttk.Frame(self.root, padding=(16, 0, 16, 16))
        footer.grid(row=2, column=0, sticky="ew")
        footer.columnconfigure(0, weight=1)

        ttk.Label(footer, textvariable=self.status_var).grid(row=0, column=0, sticky="w")
        ttk.Button(footer, text="Recargar", command=self.reload_palette).grid(row=0, column=1, padx=(8, 0))
        ttk.Button(footer, text="Restaurar actuales", command=self.restore_defaults).grid(row=0, column=2, padx=(8, 0))
        ttk.Button(footer, text="Guardar CSS", command=self.save).grid(row=0, column=3, padx=(8, 0))

    def _build_editor_tab(self, parent: ttk.Frame) -> None:
        parent.columnconfigure(0, weight=1)
        row_index = 0
        for group_name, items in MENU_GROUPS:
            frame = ttk.LabelFrame(parent, text=group_name, padding=12)
            frame.grid(row=row_index, column=0, sticky="ew", pady=(0, 12))
            frame.columnconfigure(2, weight=1)

            for item_row, (css_class, label, _) in enumerate(items):
                color_var = tk.StringVar(value=self.colors[css_class])
                self.color_vars[css_class] = color_var

                ttk.Label(frame, text=label, width=22).grid(row=item_row, column=0, sticky="w", padx=(0, 10), pady=6)

                swatch = tk.Label(frame, width=4, relief="solid", bd=1)
                swatch.grid(row=item_row, column=1, sticky="w", padx=(0, 10))
                self.swatches[css_class] = swatch

                entry = ttk.Entry(frame, textvariable=color_var, width=14)
                entry.grid(row=item_row, column=2, sticky="w", padx=(0, 10))
                entry.bind("<KeyRelease>", lambda _event, key=css_class: self.refresh_item(key))

                ttk.Button(
                    frame,
                    text="Elegir",
                    command=lambda key=css_class: self.pick_color(key),
                ).grid(row=item_row, column=3, sticky="w")

            row_index += 1

    def _build_preview_tab(self, parent: ttk.Frame) -> None:
        parent.columnconfigure(0, weight=1)
        parent.columnconfigure(1, weight=1)

        ttk.Label(
            parent,
            text="Vista previa aproximada del menu principal",
            font=("Segoe UI", 12, "bold"),
        ).grid(row=0, column=0, columnspan=2, sticky="w", pady=(0, 12))

        preview_row = 1
        for group_name, items in MENU_GROUPS:
            ttk.Label(parent, text=group_name, font=("Segoe UI", 11, "bold")).grid(
                row=preview_row, column=0, columnspan=2, sticky="w", pady=(0, 8)
            )
            preview_row += 1

            columns = 2 if len(items) > 2 else len(items)
            for idx, (css_class, label, _) in enumerate(items):
                preview = tk.Label(
                    parent,
                    text=label,
                    width=22,
                    height=4,
                    relief="solid",
                    bd=1,
                    font=("Segoe UI", 11, "bold"),
                )
                preview.grid(
                    row=preview_row + (idx // columns),
                    column=idx % columns,
                    sticky="nsew",
                    padx=(0, 12),
                    pady=(0, 12),
                )
                self.previews[css_class] = preview
            preview_row += max(1, (len(items) + columns - 1) // columns)

    def pick_color(self, css_class: str) -> None:
        current = self.color_vars[css_class].get()
        _, color = colorchooser.askcolor(color=current, title="Elegir color")
        if not color:
            return
        self.color_vars[css_class].set(normalize_hex(color))
        self.refresh_item(css_class)

    def refresh_item(self, css_class: str) -> None:
        raw_value = self.color_vars[css_class].get()
        try:
            fill = normalize_hex(raw_value)
        except ValueError:
            self.swatches[css_class].configure(bg="#ffffff")
            self.previews[css_class].configure(bg="#ffffff", fg="#1f1f1f")
            self.status_var.set("Hay colores no validos. Usa formato #rrggbb.")
            return

        border = derive_border(fill)
        text = derive_text(fill)
        self.swatches[css_class].configure(bg=fill)
        self.previews[css_class].configure(bg=fill, fg=text, highlightbackground=border)
        self.status_var.set(f"Preparado para guardar en {PALETTE_PATH.name}")

    def refresh_all(self) -> None:
        for css_class in CLASS_ORDER:
            self.refresh_item(css_class)

    def reload_palette(self) -> None:
        self.colors = load_palette()
        for css_class in CLASS_ORDER:
            self.color_vars[css_class].set(self.colors[css_class])
        self.refresh_all()
        self.status_var.set("Colores recargados desde el archivo actual.")

    def restore_defaults(self) -> None:
        for css_class in CLASS_ORDER:
            self.color_vars[css_class].set(DEFAULT_COLORS[css_class])
        self.refresh_all()
        self.status_var.set("Se restauraron los colores iniciales del editor.")

    def current_palette(self) -> dict[str, str]:
        palette: dict[str, str] = {}
        for css_class in CLASS_ORDER:
            palette[css_class] = normalize_hex(self.color_vars[css_class].get())
        return palette

    def save(self) -> None:
        try:
            palette = self.current_palette()
        except ValueError:
            messagebox.showerror("Color no valido", "Corrige los colores antes de guardar.")
            self.status_var.set("No se guardo: hay colores invalidos.")
            return

        save_palette(palette)
        self.status_var.set(f"Guardado en {PALETTE_PATH.name}. Recarga la pagina principal.")
        messagebox.showinfo("Guardado", f"Colores guardados en:\n{PALETTE_PATH}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Editor de colores del menu principal de Buen Yantar.")
    parser.add_argument(
        "--print-css",
        action="store_true",
        help="Imprime el CSS generado y sale.",
    )
    parser.add_argument(
        "--write-defaults",
        action="store_true",
        help="Escribe el archivo con la paleta por defecto y sale.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.print_css:
        print(build_palette_css(load_palette()), end="")
        return 0
    if args.write_defaults:
        save_palette(DEFAULT_COLORS.copy())
        print(PALETTE_PATH)
        return 0

    root = tk.Tk()
    style = ttk.Style(root)
    if "vista" in style.theme_names():
        style.theme_use("vista")
    editor = MenuColorEditor(root)
    editor.root.mainloop()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
